#pipeline for sample testing in azure-devops portal
trigger:
- main
pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Build
  displayName: "Run Hello world the pipeline has been changes"
  steps:
    - scripts: echo "Hello-worldss the pipeline has been change"
      displayName: 'Print Hello world'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
    - job: DeployJob
      displayName: 'Run deploy scripts'
      steps:
        - scripts: echo "Deploying"
          displayName: 'Print deploying'
